### ISSUE TITLE
Python Visualization Fails to start

### ISSUE THREAD

**Issue by Grinshpun** [bmabey/pyLDAvis#39]
Mr. Mabey

My original problem has come back after I used the "gensim_speed" branch variation of the bug fix for 1.3.1. The original problem #33 that you closed last week appears to be deeper than originally thought. I an running Win 10, Python 3.4.3.6, and pyLDAvis 1.3.1 with the gensim_speed correction. I used the ipython -i at the commend prompt to enter the intractive mode, loaded the model and and ran prepare, and got the same printout as it was in #33 . PFA the screenshots with the problem. I suspect I'm doing something wrong - but I have no idea what can it possibly be, since I'm only running the simplest commands.

Thanks
Vadim

![nodiagram1](https://cloud.githubusercontent.com/assets/15304277/11017971/1644c70e-8581-11e5-8252-a2d7ed75bb06.png)
![nodiagram2](https://cloud.githubusercontent.com/assets/15304277/11017972/197b4cd6-8581-11e5-8341-817eca92ccd4.png)
![nodiagram3](https://cloud.githubusercontent.com/assets/15304277/11017975/1c5ba25c-8581-11e5-9d70-29518bedc28e.png)

**Comment by bmabey** [comment]
As I said in #33 you need to be using the IPython **notebook** if you want to display the visualization inline. It will not work with the IPython shell or QT frontends since the viz requires javascript and CSS. Start up ipython with `ipython notebook` and run your same commands to see the visualization.

Alternatively, if you don't want to use IPython notebook you can have `pyLDAvis` start up a webserver with the [`show`](https://pyldavis.readthedocs.org/en/latest/modules/API.html#pyLDAvis.show) function that I also mentioned in #33:
```python
vis_data = pyLDAvis.gensim.prepare(lda, corpus, dictionary)
pyLDAvis.show(vis_data)
```
